### ISSUE TITLE
Heroku dyno doesn't stay running - may be fixable

### ISSUE THREAD

**Issue by naclcaleb** [OOPS-Studio/Battleship-ONLINE-Server#2]
Obviously, the biggest downside to using the free Heroku plan is that your dynos shut off after 30min of inactivity.

But it turns out, it's pretty easy to trick it. If you send it HTTP requests every 15 minutes or so, it will not shut off (it works for me anyway). I just run this Python script as a background process on my computer:

```
import os
import time

app_name = "your_app_name"

while True:
	os.system("curl https://" + app_name + ".herokuapp.com")
	time.sleep(900)
```

Basically it runs the `curl` command every 15 seconds (which just sends an HTTP request). Now Heroku thinks it's getting activity. My dyno has been running all day, and I haven't been doing anything with it.

**Comment by OOPS-Studio** [comment]
Haha, Thanks, Caleb! ;) I know that! :) I have my Heroku Dyno set up to automatically boot up when it receives traffic, so I don't have to worry about that! ;) The reason it keeps giving you errors when you try and access the page is that I _want_ it to stay off! :) I don't want it to use up my dyno hours, so I manually turn it off! :) I'll let it stay on once I actually release a game for it. For now, I'll just boot it up when I need to test something/somebody wants to play! ;)

**Comment by naclcaleb** [comment]
Meh, ok, just making sure XD

Mine's set up like that too, but it takes a significant amount of time to load for me. And I use mine a lot, so it doesn't have much effect on my dyno hours.

**Comment by naclcaleb** [comment]
And also, it seems like they give you a lot of dyno hours per month...I'd only have to have it down maybe a week or so and I'd be fine. 

Although this is pretty much my only app on there, and I don't know if it's on a per app basis or not.

**Comment by OOPS-Studio** [comment]
1. Haha, Okay! :P Thanks! ;)
2. Well, okay! :) I'm glad it works for you! ;)
3. Yes, but I use it so infrequently (I do most of my coding offline, and then test it online every now and then) that I wouldn't need it on so frequently... Plus, I wouldn't want to be forced to not code for 1 week out of every month... :P
4. No. It's not per-app... It's per-account... For all the apps on the account! ;-;
